---
- name: copy post publish script
  copy:
    src: scalelite_post_publish.rb
    dest: /usr/local/bigbluebutton/core/scripts/post_publish/scalelite_post_publish.rb
    mode: 644

- name: copy scalelite yml
  copy:
    src: scalelite.yml
    dest: /usr/local/bigbluebutton/core/scripts/scalelite.yml
    mode: 644

- name: Ensure group "scalelite-spool" exists
  group:
    name: scalelite-spool
    state: present
    gid: 2000

- name: Ensure user "bigbluebutton" in group "scalelite-spool"
  user:
    name: bigbluebutton
    groups: scalelite-spool
    append: yes


- name: make shared NFS Scalelite recording repository
  run_once: true
  file:
    path: "/mnt/scalelite-recordings/var/bigbluebutton/{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0775"
  with_items:
    - "recording/scalelite"
    - "published"
    - "unpublished"


- name: make shared NFS Scalelite recording repository (spool)
  run_once: true
  file:
    path: "/mnt/scalelite-recordings/var/bigbluebutton/spool"
    state: directory
    owner: "1000"
    group: scalelite-spool
    mode: "0775"
